### ISSUE TITLE
rpc error: code = Unknown desc = failed to find gpu id

### ISSUE THREAD

**Issue by zishen** [volcano-sh/devices#10]
Maybe is a bug

The yaml is 
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: mindx-dls-gpu
  namespace: vcjob
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 3
  queue: default
  tasks:
  - name: "default-1p"
    replicas: 1
    template:
      metadata:
        labels:
          app: tf
      spec:
        containers:
        - image: nvidia-train:v1
          imagePullPolicy: IfNotPresent
          name: cuda-container
          command:
          - "/bin/bash"
          - "-c"
          #- "chmod 777 -R /job;cd /job/code/ModelZoo_Resnet50_HC; bash train_start.sh"
          args: [ "while true; do sleep 3000000; done;"  ]
          resources:
            requests:
              volcano.sh/gpu-number: 1
            limits:
              volcano.sh/gpu-number: 1
          volumeMounts:
          - name: timezone
            mountPath: /etc/timezone
          - name: localtime
            mountPath: /etc/localtime
        nodeSelector:
          accelerator: nvidia-tesla-v100
        volumes:
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/timezone
  name:
        restartPolicy: OnFailure`
```

And I use "olcano.sh/gpu-memory" resource is error:
```
Nov 10 20:11:23 ubuntu560 kubelet[26515]: E1110 20:11:23.149895   26515 manager.go:374] Failed to allocate device plugin resource for pod 28bc8549-e3b9-40f6-8adb-7830f967d97b: rpc error: code = Unknown desc = failed to find gpu id
Nov 10 20:11:23 ubuntu560 kubelet[26515]: W1110 20:11:23.149941   26515 predicate.go:74] Failed to admit pod mindx-dls-gpu-default-1p-0_vcjob(28bc8549-e3b9-40f6-8adb-7830f967d97b) - Update plugin resources failed due to rpc error: code = Unknown desc = failed to find gpu id, which is unexpected.
```

env:
```
volcano:v1.0.1
volcano-deviceplugin:v1.0.0
os:ubuntu 18.04  amd64
```

so is volcano.sh/gpu-memory support?

**Comment by zishen** [comment]
![volcano-deviceplugin](https://user-images.githubusercontent.com/7522079/98675323-11c2a400-2395-11eb-89d4-340433c133e7.PNG)
The error picture is above.

**Comment by hzxuzhonghu** [comment]
cc @william-wang @Thor-wl

**Comment by Thor-wl** [comment]
OK, let me have a try.

**Comment by mmhhss** [comment]
I met the same problem too
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod1
spec:
  schedulerName: volcano
  containers:
    - name: cuda-container
      image: horovod_gpu:v2.0
      command: ["sleep", "100"]
      resources:
        limits:
          volcano.sh/gpu-memory: "1024"
```

```
kubectl describe pod gpu-pod1
Name:         gpu-pod1
Namespace:    default
Priority:     0
Node:         cmp-node6/
Start Time:   Mon, 16 Nov 2020 18:14:08 +0800
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"gpu-pod1","namespace":"default"},"spec":{"containers":[{"command":["s...
              scheduling.k8s.io/group-name: podgroup-e9a8ebc2-da88-402a-a8ea-c719e52fede3
Status:       Failed
Reason:       UnexpectedAdmissionError
Message:      Pod Update plugin resources failed due to rpc error: code = Unknown desc = failed to find gpu id, which is unexpected.
IP:           
Containers:
  cuda-container:
    Image:      horovod_gpu:v2.0
    Port:       <none>
    Host Port:  <none>
    Command:
      sleep
      100
    Limits:
      volcano.sh/gpu-memory:  1024
    Requests:
      volcano.sh/gpu-memory:  1024
    Environment:              <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kr9kv (ro)
Volumes:
  default-token-kr9kv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kr9kv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                    Age   From                Message
  ----     ------                    ----  ----                -------
  Normal   Scheduled                 30s   volcano             Successfully assigned default/gpu-pod1 to cmp-node6
  Warning  UnexpectedAdmissionError  30s   kubelet, cmp-node6  Update plugin resources failed due to rpc error: code = Unknown desc = failed to find gpu id, which is unexpected.
```

**Comment by william-wang** [comment]
@Thor-wl is there any progress for this issue?

**Comment by wpeng102** [comment]
Please check：
1）If the volcano scheduler contains GPU share feature
2）If the `volcano-scheduler-configmap` enable `predicate.GPUSharingEnable` refer (https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_gpu_sharing.md)
3) If the `volcano-scheduler` cluster role has `patch` role for "pods", "pods/status"

If not free install latest volcano just replace volcano scheduler image maybe  miss step 2) and 3).

In my test env, it works well:
```
root@mscpptb00006:~/peng# cat test1.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: OnFailure
  schedulerName: volcano
  containers:
  - image: nvidia/cuda:10.1-base-ubuntu18.04
    name: pod1-ctr
    command: ["sleep"]
    args: ["100000"]
    resources:
      limits:
        volcano.sh/gpu-memory: 1024
```
```
root@mscpptb00006:~/peng# kubectl get po
NAME       READY   STATUS    RESTARTS   AGE
gpu-test   1/1     Running   0          2s

root@mscpptb00006:~/peng# kubectl exec -it gpu-test nvidia-smi
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
Wed Dec  2 09:34:46 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:21:01.0 Off |                    0 |
| N/A   27C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```
